#                               POK header
#
# The following file is a part of the POK project. Any modification should
# be made according to the POK licence. You CANNOT use this file or a part
# of a file for your own project.
#
# For more information on the POK licence, please see our LICENCE FILE
#
# Please follow the coding guidelines described in doc/CODING_GUIDELINES
#
#                                      Copyright (c) 2007-2022 POK team

target:
    arch: x86
    bsp: x86-qemu

partitions:
    - name: pr1
      features: [timer, console, libc, assert]
      semaphores: 1
      scheduler: static
      threads:
          count: 2
          features: [sleep, suspend]
      size: 130kB
      objects: ["main.o", "activity.o"]
    - name: pr2
      features: [timer, console, libc, assert]
      threads:
          count: 2
      size: 130kB
      objects: ["main.o", "activity.o"]
    - name: pr3
      features: [timer, console, libc, assert]
      threads:
          count: 2
      size: 130kB
      objects: ["main.o", "activity.o"]

kernel:
    features: [debug_part]
    partition_sched: edf
    scheduler:
        slots:
            - partition: pr1
              period: 5s
              complete_time: 1s
              deadline: 5s
            - partition: pr2
              period: 4s
              complete_time: 2s
              deadline: 4s
            - partition: pr2
              period: 3s
              complete_time: 1s
              deadline: 3s
